---
title: "p8105_hw6_eb3516"
author: "Liz Bekerman"
date: "2023-12-02"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
```

```{r}
options(
  ggplot2.continuous.colour="viridis",
  ggplot2.continuous.fill="viridis")

scale_colour_discrete=scale_colour_viridis_d
scale_fill_discrete=scale_fill_viridis_d
```

## Problem 2
First, we import the weather data.

```{r}
weather_df=
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var=c("PRCP", "TMIN", "TMAX"),
    date_min="2022-01-01",
    date_max="2022-12-31") |>
  mutate(
    name=recode(id, USW00094728="CentralPark_NY"),
    tmin=tmin/10,
    tmax=tmax/10) |>
  select(name, id, everything())
```

The linear model predicts `tmax` using `tmin` and `prcp`.

Next, we will run 5000 bootstraps to estimate R-squared and log(B1*B2).

```{r}
weather_bootstrap = weather_df |>
  bootstrap(n=5000) |>
  mutate(
    models=map(strap, \(weather_df) lm(tmax~tmin+prcp, weather_df)),
    results=map(models, broom::tidy),
    rsq=map(models, broom::glance)
  ) |>
  select(-strap, -models) |>
  unnest(results) |>
  filter(term %in% c("tmin", "prcp")) |>
  group_by(.id) |>
  mutate(B1x2=sum(estimate)) |>
  select(B1x2, rsq) |>
  unnest(rsq) |>
  janitor::clean_names() |>
  select(id, b1x2, r_squared) |> unique()
```
  
Next, we'll calculate the confidence intervals.

```{r}
weather_bootstrap |>
  summarize(
    rsq_lower_ci=quantile(r_squared, 0.025),
    rsq_upper_ci=quantile(r_squared, 0.975)
  )
  
weather_bootstrap |>
  summarize(
    beta_lower_ci=quantile(b1x2, 0.025),
    beta_upper_ci=quantile(b1x2, 0.975)
  )
``` 



